export const ACCOUNT_CREATION_STEP_SET = 'ACCOUNT_CREATION_STEP_SET';

export const ACCOUNT_NAME_SET = 'ACCOUNT_NAME_SET';
export const PASSWORD_SET = 'PASSWORD_SET';

export const SEED_VALUES_SET = 'SEED_VALUES_SET';
export const MISSING_SEED_INDEX = 'MISSING_SEED_INDEX';
export const CONTINUE_BUTTON_SHOW = 'CONTINUE_BUTTON_SHOW';

export const ACCOUNT_CREATION_TAB_VALUE_SET = 'ACCOUNT_CREATION_TAB_VALUE_SET';
