import { API_BASE_URL } from './common';

export const COINGECKO_GET_IN_PROGRESS = 'COINGECKO_GET_IN_PROGRESS';
export const COINGECKO_GET_SUCCESS = 'COINGECKO_GET_SUCCESS';
export const COINGECKO_GET_ERROR = 'COINGECKO_GET_ERROR';

export const COINGECKO_GET_URL = `${API_BASE_URL}/accounts`;
