import { API_BASE_URL } from './common';

export const CONFIGURATION_GET_IN_PROGRESS = 'CONFIGURATION_GET_IN_PROGRESS';
export const CONFIGURATION_GET_SUCCESS = 'CONFIGURATION_GET_SUCCESS';
export const CONFIGURATION_GET_ERROR = 'CONFIGURATION_GET_ERROR';

export const CONFIGURATION_GET_URL = `${API_BASE_URL}/config`;

export const CONFIGURATION_SETUP_SET = 'CONFIGURATION_SETUP_SET';
export const CONFIGURATION_CHAIN_BROADCAST_MODE_SET = 'CONFIGURATION_CHAIN_BROADCAST_MODE_SET';
export const CONFIGURATION_CHAIN_FEES_SET = 'CONFIGURATION_CHAIN_FEES_SET';
export const CONFIGURATION_CHAIN_GAS_ADJUSTMENT_SET = 'CONFIGURATION_CHAIN_GAS_ADJUSTMENT_SET';
export const CONFIGURATION_CHAIN_GAS_PRICES_SET = 'CONFIGURATION_CHAIN_GAS_PRICES_SET';
export const CONFIGURATION_CHAIN_GAS_SET = 'CONFIGURATION_CHAIN_GAS_SET';
export const CONFIGURATION_CHAIN_ID_SET = 'CONFIGURATION_CHAIN_ID_SET';
export const CONFIGURATION_CHAIN_RPC_ADDRESS_SET = 'CONFIGURATION_CHAIN_RPC_ADDRESS_SET';
export const CONFIGURATION_CHAIN_SIMULATE_AND_EXECUTE_SET = 'CONFIGURATION_CHAIN_SIMULATE_AND_EXECUTE_SET';
export const CONFIGURATION_CHAIN_TRUST_NODE_SET = 'CONFIGURATION_CHAIN_TRUST_NODE_SET';

export const CONFIGURATION_PUT_IN_PROGRESS = 'CONFIGURATION_PUT_IN_PROGRESS';
export const CONFIGURATION_PUT_SUCCESS = 'CONFIGURATION_PUT_SUCCESS';
export const CONFIGURATION_PUT_ERROR = 'CONFIGURATION_PUT_ERROR';

export const CONFIGURATION_PUT_URL = `${API_BASE_URL}/config`;
