export const DISTRIBUTION_TAB_VALUE_SET = 'DISTRIBUTION_TAB_VALUE_SET';

export const WITHDRAW_SEARCH_VALIDATOR_LIST_SET = 'WITHDRAW_SEARCH_VALIDATOR_LIST_SET';
export const WITHDRAW_SORT_ORDER_BY_SET = 'WITHDRAW_SORT_ORDER_BY_SET';
export const WITHDRAW_SORT_ORDER_SET = 'WITHDRAW_SORT_ORDER_SET';
export const WITHDRAW_DIALOG_SHOW = 'WITHDRAW_DIALOG_SHOW';
export const WITHDRAW_DIALOG_HIDE = 'WITHDRAW_DIALOG_HIDE';
export const WITHDRAW_PASSWORD_SET = 'WITHDRAW_PASSWORD_SET';
export const WITHDRAW_SUCCESS_DIALOG_SHOW = 'WITHDRAW_SUCCESS_DIALOG_SHOW';
export const WITHDRAW_SUCCESS_DIALOG_HIDE = 'WITHDRAW_SUCCESS_DIALOG_HIDE';

export const WITHDRAW_ALL_PASSWORD_SET = 'WITHDRAW_ALL_PASSWORD_SET';
export const WITHDRAW_ALL_DIALOG_SHOW = 'WITHDRAW_ALL_DIALOG_SHOW';
export const WITHDRAW_ALL_DIALOG_HIDE = 'WITHDRAW_ALL_DIALOG_HIDE';

export const WITHDRAW_ALL_IN_PROGRESS = 'WITHDRAW_ALL_IN_PROGRESS';
export const WITHDRAW_ALL_SUCCESS = 'WITHDRAW_ALL_SUCCESS';
export const WITHDRAW_ALL_ERROR = 'WITHDRAW_ALL_ERROR';

export const WITHDRAW_IN_PROGRESS = 'WITHDRAW_IN_PROGRESS';
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_ERROR = 'WITHDRAW_ERROR';
