export const KEYS_FETCH_IN_PROGRESS = 'KEYS_FETCH_IN_PROGRESS';
export const KEYS_FETCH_SUCCESS = 'KEYS_FETCH_SUCCESS';
export const KEYS_FETCH_ERROR = 'KEYS_FETCH_ERROR';

export const KEYS_ADD_IN_PROGRESS = 'KEYS_ADD_IN_PROGRESS';
export const KEYS_ADD_SUCCESS = 'KEYS_ADD_SUCCESS';
export const KEYS_ADD_ERROR = 'KEYS_ADD_ERROR';

export const ACTIVE_ACCOUNT_SET = 'ACTIVE_ACCOUNT_SET';

export const KEYS_DELETE_IN_PROGRESS = 'KEYS_DELETE_IN_PROGRESS';
export const KEYS_DELETE_SUCCESS = 'KEYS_DELETE_SUCCESS';
export const KEYS_DELETE_ERROR = 'KEYS_DELETE_ERROR';

export const LOCAL_STORAGE_SEED_SET = 'LOCAL_STORAGE_SEED_SET';
