export const PROFILE_POPOVER_SHOW = 'PROFILE_POPOVER_SHOW';
export const PROFILE_POPOVER_HIDE = 'PROFILE_POPOVER_HIDE';

export const DELETE_ACCOUNT_DIALOG_SHOW = 'DELETE_ACCOUNT_DIALOG_SHOW';
export const DELETE_ACCOUNT_DIALOG_HIDE = 'DELETE_ACCOUNT_DIALOG_HIDE';
export const DELETE_ACCOUNT_PASSWORD_SET = 'DELETE_ACCOUNT_PASSWORD_SET';

export const NEW_ACCOUNT_NAME_SET = 'NEW_ACCOUNT_NAME_SET';
export const NEW_ACCOUNT_PASSWORD_SET = 'NEW_ACCOUNT_PASSWORD_SET';
export const SEED_SET = 'SEED_SET';

export const FAUCET_TRANSFER_FETCH_IN_PROGRESS = 'FAUCET_TRANSFER_FETCH_IN_PROGRESS';
export const FAUCET_TRANSFER_FETCH_SUCCESS = 'FAUCET_TRANSFER_FETCH_SUCCESS';
export const FAUCET_TRANSFER_FETCH_ERROR = 'FAUCET_TRANSFER_FETCH_ERROR';
