export const STACKING_TAB_VALUE_SET = 'STACKING_TAB_VALUE_SET';

export const DELEGATE_ACTIVE_LIST_SHOW = 'DELEGATE_ACTIVE_LIST_SHOW';
export const DELEGATE_ACTIVE_LIST_HIDE = 'DELEGATE_ACTIVE_LIST_HIDE';
export const DELEGATE_DIALOG_SHOW = 'DELEGATE_DIALOG_SHOW';
export const DELEGATE_DIALOG_HIDE = 'DELEGATE_DIALOG_HIDE';
export const DELEGATE_AMOUNT_SET = 'DELEGATE_AMOUNT_SET';
export const DELEGATE_PASSWORD_SET = 'DELEGATE_PASSWORD_SET';
export const DELEGATE_SUCCESS_DIALOG_SHOW = 'DELEGATE_SUCCESS_DIALOG_SHOW';
export const DELEGATE_SUCCESS_DIALOG_HIDE = 'DELEGATE_SUCCESS_DIALOG_HIDE';

export const SEARCH_VALIDATOR_LIST_SET = 'SEARCH_VALIDATOR_LIST_SET';
export const SORT_ORDER_SET = 'SORT_ORDER_SET';
export const SORT_ORDER_BY_SET = 'SORT_ORDER_BY_SET';

export const UN_BOND_SEARCH_VALIDATOR_LIST_SET = 'UN_BOND_SEARCH_VALIDATOR_LIST_SET';
export const UN_BOND_SORT_ORDER_SET = 'UN_BOND_SORT_ORDER_SET';
export const UN_BOND_SORT_ORDER_BY_SET = 'UN_BOND_SORT_ORDER_BY_SET';
export const UN_BOND_DIALOG_SHOW = 'UN_BOND_DIALOG_SHOW';
export const UN_BOND_DIALOG_HIDE = 'UN_BOND_DIALOG_HIDE';
export const UN_BOND_AMOUNT_SET = 'UN_BOND_AMOUNT_SET';
export const UN_BOND_PASSWORD_SET = 'UN_BOND_PASSWORD_SET';
export const UN_BOND_SUCCESS_DIALOG_SHOW = 'UN_BOND_SUCCESS_DIALOG_SHOW';
export const UN_BOND_SUCCESS_DIALOG_HIDE = 'UN_BOND_SUCCESS_DIALOG_HIDE';

export const RE_DELEGATE_SEARCH_VALIDATOR_LIST_SET = 'RE_DELEGATE_SEARCH_VALIDATOR_LIST_SET';
export const RE_DELEGATE_SORT_ORDER_SET = 'RE_DELEGATE_SORT_ORDER_SET';
export const RE_DELEGATE_SORT_ORDER_BY_SET = 'RE_DELEGATE_SORT_ORDER_BY_SET';
export const RE_DELEGATE_DIALOG_SHOW = 'RE_DELEGATE_DIALOG_SHOW';
export const RE_DELEGATE_DIALOG_HIDE = 'RE_DELEGATE_DIALOG_HIDE';
export const RE_DELEGATE_AMOUNT_SET = 'RE_DELEGATE_AMOUNT_SET';
export const RE_DELEGATE_PASSWORD_SET = 'RE_DELEGATE_PASSWORD_SET';
export const RE_DELEGATE_TO_ADDRESS_SET = 'RE_DELEGATE_TO_ADDRESS_SET';
export const RE_DELEGATE_SUCCESS_DIALOG_SHOW = 'RE_DELEGATE_SUCCESS_DIALOG_SHOW';
export const RE_DELEGATE_SUCCESS_DIALOG_HIDE = 'RE_DELEGATE_SUCCESS_DIALOG_HIDE';

export const VALIDATORS_LIST_FETCH_IN_PROGRESS = 'VALIDATORS_LIST_FETCH_IN_PROGRESS';
export const VALIDATORS_LIST_FETCH_SUCCESS = 'VALIDATORS_LIST_FETCH_SUCCESS';
export const VALIDATORS_LIST_FETCH_ERROR = 'VALIDATORS_LIST_FETCH_ERROR';

export const DELEGATIONS_VALIDATORS_LIST_FETCH_IN_PROGRESS = 'DELEGATIONS_VALIDATORS_LIST_FETCH_IN_PROGRESS';
export const DELEGATIONS_VALIDATORS_LIST_FETCH_SUCCESS = 'DELEGATIONS_VALIDATORS_LIST_FETCH_SUCCESS';
export const DELEGATIONS_VALIDATORS_LIST_FETCH_ERROR = 'DELEGATIONS_VALIDATORS_LIST_FETCH_ERROR';

export const RE_DELEGATE_IN_PROGRESS = 'RE_DELEGATE_IN_PROGRESS';
export const RE_DELEGATE_ERROR = 'RE_DELEGATE_ERROR';
export const RE_DELEGATE_SUCCESS = 'RE_DELEGATE_SUCCESS';

export const DELEGATION_IN_PROGRESS = 'DELEGATION_IN_PROGRESS';
export const DELEGATION_ERROR = 'DELEGATION_ERROR';
export const DELEGATION_SUCCESS = 'DELEGATION_SUCCESS';

export const ACTIVE_VALIDATORS_LIST_FETCH_IN_PROGRESS = 'ACTIVE_VALIDATORS_LIST_FETCH_IN_PROGRESS';
export const ACTIVE_VALIDATORS_LIST_FETCH_SUCCESS = 'ACTIVE_VALIDATORS_LIST_FETCH_SUCCESS';
export const ACTIVE_VALIDATORS_LIST_FETCH_ERROR = 'ACTIVE_VALIDATORS_LIST_FETCH_ERROR';

export const IN_ACTIVE_VALIDATORS_LIST_FETCH_IN_PROGRESS = 'IN_ACTIVE_VALIDATORS_LIST_FETCH_IN_PROGRESS';
export const IN_ACTIVE_VALIDATORS_LIST_FETCH_SUCCESS = 'IN_ACTIVE_VALIDATORS_LIST_FETCH_SUCCESS';
export const IN_ACTIVE_VALIDATORS_LIST_FETCH_ERROR = 'IN_ACTIVE_VALIDATORS_LIST_FETCH_ERROR';

export const ACTIVE_BUTTON_SWITCH_SET = 'ACTIVE_BUTTON_SWITCH_SET';
export const VALIDATORS_LIST_FETCH_SET = 'VALIDATORS_LIST_FETCH_SET';

export const UN_BOND_IN_PROGRESS = 'UN_BOND_IN_PROGRESS';
export const UN_BOND_ERROR = 'UN_BOND_ERROR';
export const UN_BOND_SUCCESS = 'UN_BOND_SUCCESS';

export const OUT_OF_GAS = 'OUT_OF_GAS';
