export const TRANSACTIONS_TAB_VALUE_SET = 'TRANSACTIONS_TAB_VALUE_SET';

export const TRANSACTION_HASH_IN_PROGRESS = 'TRANSACTION_HASH_IN_PROGRESS';
export const TRANSACTION_HASH_SUCCESS = 'TRANSACTION_HASH_SUCCESS';
export const TRANSACTION_HASH_ERROR = 'TRANSACTION_HASH_ERROR';
export const TRANSACTION_HASH_INTERVAL_SET = 'TRANSACTION_HASH_INTERVAL_SET';

export const SENT_TRANSACTIONS_FETCH_IN_PROGRESS = 'SENT_TRANSACTIONS_FETCH_IN_PROGRESS';
export const SENT_TRANSACTIONS_FETCH_SUCCESS = 'SENT_TRANSACTIONS_FETCH_SUCCESS';
export const SENT_TRANSACTIONS_FETCH_ERROR = 'SENT_TRANSACTIONS_FETCH_ERROR';

export const RECEIVED_TRANSACTIONS_FETCH_IN_PROGRESS = 'RECEIVED_TRANSACTIONS_FETCH_IN_PROGRESS';
export const RECEIVED_TRANSACTIONS_FETCH_SUCCESS = 'RECEIVED_TRANSACTIONS_FETCH_SUCCESS';
export const RECEIVED_TRANSACTIONS_FETCH_ERROR = 'RECEIVED_TRANSACTIONS_FETCH_ERROR';

export const OTHER_TRANSACTIONS_FETCH_IN_PROGRESS = 'OTHER_TRANSACTIONS_FETCH_IN_PROGRESS';
export const OTHER_TRANSACTIONS_FETCH_SUCCESS = 'OTHER_TRANSACTIONS_FETCH_SUCCESS';
export const OTHER_TRANSACTIONS_FETCH_ERROR = 'OTHER_TRANSACTIONS_FETCH_ERROR';
