export const TAB_VALUE_SET = 'TAB_VALUE_SET';

export const WALLET_TRANSACTION_SHOW = 'WALLET_TRANSACTION_SHOW';
export const WALLET_TAB_SHOW = 'WALLET_TAB_SHOW';
export const TRANSACTION_TAB_VALUE_SET = 'TRANSACTION_TAB_VALUE_SET';

export const ADDRESS_TO_SEND_SET = 'ADDRESS_TO_SEND_SET';
export const TOKENS_TO_SEND_SET = 'TOKENS_TO_SEND_SET';
export const TOKEN_TYPE_SET = 'TOKEN_TYPE_SET';
export const GAS_PRICE_SET = 'GAS_PRICE_SET';
export const GAS_PRICE_INCREMENT_SET = 'GAS_PRICE_INCREMENT_SET';
export const GAS_PRICE_DECREMENT_SET = 'GAS_PRICE_DECREMENT_SET';

export const PASSWORD_SET = 'PASSWORD_SET';

export const WALLET_DETAILS_GET_IN_PROGRESS = 'WALLET_DETAILS_GET_IN_PROGRESS';
export const WALLET_DETAILS_GET_SUCCESS = 'WALLET_DETAILS_GET_SUCCESS';
export const WALLET_DETAILS_GET_ERROR = 'WALLET_DETAILS_GET_ERROR';

export const TRANSFER_TOKENS_IN_PROGRESS = 'TRANSFER_TOKENS_IN_PROGRESS';
export const TRANSFER_TOKENS_SUCCESS = 'TRANSFER_TOKENS_SUCCESS';
export const TRANSFER_TOKENS_ERROR = 'TRANSFER_TOKENS_ERROR';
