const variables = {
    en: {
        wallet_creation: 'Wallet Creation',
        go_back: 'Go Back',
        enter_account_name: 'Enter Account Name',
        create_an_account: 'Create An Account',
        create_new_account: 'Create New Account',
        enter_password: 'Enter Password',
        wallet_successful: 'Wallet Successfully Created!',
        address: 'Address',
        pub_key: 'Public Key',
        seed: 'Seed',
        note: 'Note',
        continue: 'Continue',
        copy_keys: 'Copy your keys to a secure location. Remember, we don\'t store any of your keys in our databases.',
        enter_missing_seed: 'Enter missing seed words to continue..',
        quick_transact: 'Quick Transact',
        recover_account: 'Recover Account',
        exit: 'Exit',
        dashboard: 'Dashboard',
        my_wallets: 'My Wallets',
        send_receive: 'Send/Receive',
        transactions: 'Transactions',
        received: 'Received',
        sent: 'Sent',
        other: 'Other',
        wallet: 'Wallet',
        staking: 'Staking',
        distribution: 'Distribution',
        receive: 'Receive',
        send: 'Send',
        show_qr: 'Show QR code to Receive Tokens',
        scan_qr: 'Scan QR Code.',
        enter_address: 'Enter Address',
        address_to_send: 'Address To Send',
        tokens_to_send: 'Tokens To Send',
        gas_price: 'Gas Price',
        password: 'Password',
        tokens: 'Tokens',
        enter_gas_price: 'Enter Gas Price',
        delegate: 'Delegate',
        re_delegate: 'Re-Delegate',
        un_bond: 'UnBond',
        active: 'Active',
        in_active: 'InActive',
        validators_list: 'Validators List',
        search: 'Search...',
        enter_amount: 'Enter Amount...',
        delegating: 'Delegating',
        to: 'to',
        operator_address: 'Operator Address',
        commission_rate: 'Commission Rate',
        amount: 'Amount',
        TI_delegate: 'Transaction Initiated, Delegate',
        tx_hash: 'tx#',
        close: 'close',
        TI_de_delegate: 'Transaction Initiated, Re-Delegate',
        from: 'from',
        re_delegating: 'Re-Delegating',
        to_address: 'To Address',
        shares: 'Shares',
        TI_un_bond: 'Transaction Initiated, UnBond',
        un_bonding: 'UnBonding',
        withdraw: 'Withdraw',
        withdraw_rewards: 'Withdraw Rewards',
        withdraw_all: 'Withdraw All Rewards',
        TI_withdraw: 'Withdraw Rewards Transaction Initiated',
        successfully_withdrawn: 'Successfully Withdrawn Rewards',
        all: 'All',
        available_tokens: 'Available Tokens',
        enter_new_account_name: 'Enter New Account Name',
        enter_new_account_password: 'Enter New Account Password',
        enter_seed: 'Enter Seed',
        delete: 'Delete',
        are_you_sure: 'Are You Sure',
        do_you_want_to: 'Do you want to',
        delete_account: 'Delete Account',
        faucet: 'Faucet',
        export_seed: 'Export Seed',
        dVpn: 'dVPN',
        dVpn_list: 'dVPN LIST',
        session_history: 'Session History',
        failed: 'Failed!',

        // Error Codes
        ec_1: 'Failed to parse the request body',
        ec_2: 'Failed to parse the query params',
        ec_3: 'Failed to validate request body',
        ec_4: 'Failed to decode the address',
        ec_5: 'Failed to prepare the message',
        ec_6: 'Failed to broadcast the transaction',
        ec_7: 'Failed to get validator',
        ec_8: 'Failed to get validators',
        ec_9: 'Failed to get delegator validators',
        ec_10: 'Failed to get transaction',
        ec_11: 'Failed to get transactions',
        ec_12_account: 'Failed to query the account',
        ec_13_account: 'Failed to get delegator delegations',
        ec_14_account: 'Failed to get delegator validators',
        ec_12_config: 'Failed to call update hook',
        ec_13_config: 'Failed to save config',
        ec_12_key: 'Failed to list the keys',
        ec_13_key: 'Duplicate key name',
        ec_14_key: 'Failed creating mnemonic',
        ec_15_key: 'Failed to invalid mnemonic',
        ec_16_key: 'Failed to creating key',
        ec_17_key: 'Failed to deleting key',
        recover_add_account: 'Recover & Add Account',
    },
};

export default variables;
